version: '3.8'

services:
  app:
    build:
      context: .
      target: production
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
      - redis
    command: sh -c 'while ! nc -z db 5432; do sleep 1; done; uvicorn app.main:app --host 0.0.0.0 --port 8080'

  db:
    image: postgres
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - ./postgres:/var/lib/postgresql/data

  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis_data:/data

  worker:
    build:
      context: .
      target: production
    env_file:
      - .env
    depends_on:
      - redis
      - db
      - app
    command: rq worker --url redis://redis:6379

  testing:
    build:
      context: .
      target: testing
    volumes:
      - .:/app
    env_file:
      - .env
