version: '3.8'

services:
  app:
    build:
      context: .
      target: production
    ports:
      - "8080:8080"
    volumes:
      - .:/app

  testing:
    build:
      context: .
      target: testing
    volumes:
      - .:/app
